name: ci-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:
  test:
    name: Test
    run-on: ubuntu-latest
    steps:
      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-versoin: ^1.22
        id: go
      - name: Checkout go into go module repo
        uses: actions/checkout@v2
      - name: Test
        run: make gotest
